### PR TITLE
localize addon for koKR

### PR DESCRIPTION
**Pull request by WetU**
Localized in koKR

### CODE REVIEW

**Comment by ls-** [comment]
Hi!

This one will have to sit here for a while 😞

**Comment by ls-** [comment]
Hi! It's been awhile, sorry T_T

So I finally started working on adding localisation support. Could you please add missing lines (they're commented out) to [this file](https://github.com/ls-/ls_Toasts/blob/localisation/locales/koKR.lua)?

**Comment by WetU** [comment]
Good to see you again :)

I will translate these lines as soon as possible!

**Comment by ls-** [comment]
No need to hurry :D

**Pull request closed without merging**
